version: '3.8'
services:
  mysql:
    image: mysql:8.0.29
    restart: unless-stopped
    container_name: mysql
    ports:
      - "127.0.0.1:3307:3306"
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: ${mysql_root_password}
      MYSQL_USER: user_flask
      MYSQL_PASSWORD: ${db_password}
      MYSQL_DATABASE: ${db_name}
    volumes:
      - .db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${mysql_root_password}"]
      timeout: 5s
      retries: 10
      interval: 5s
  web:
    build:
      context: . 
      dockerfile: dockerfile
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    env_file:
      - .env
    environment:
      FLASK_APP: run.py
      FLASK_ENV: development
    depends_on:
      mysql:
        condition: service_healthy